export type SourceSeed = {
  name: string;
  nameZh: string;
  rssUrl: string;
  lang: "en" | "zh";
  dailyLimit: number;
  defaultCategory: string;
  defaultSchool?: string;
};

// Initial feeds. Sources are editable at runtime via the Source table / admin,
// so this list only seeds the first run. Most Chinese outlets do not expose
// public RSS, so they can be added once a feed or a custom scraper is ready.
export const SOURCES: SourceSeed[] = [
  {
    name: "ScienceDaily Mind & Brain",
    nameZh: "科学日报·心智与大脑",
    rssUrl: "https://www.sciencedaily.com/rss/mind_brain.xml",
    lang: "en",
    dailyLimit: 12,
    defaultCategory: "research",
  },
  {
    name: "PsyPost",
    nameZh: "PsyPost 心理学",
    rssUrl: "https://www.psypost.org/feed",
    lang: "en",
    dailyLimit: 10,
    defaultCategory: "research",
  },
  {
    name: "SciTechDaily",
    nameZh: "科技日报·健康科学",
    rssUrl: "https://scitechdaily.com/feed",
    lang: "en",
    dailyLimit: 10,
    defaultCategory: "research",
  },
  {
    name: "MedicalXpress",
    nameZh: "医学快讯",
    rssUrl: "https://medicalxpress.com/rss-feed/",
    lang: "en",
    dailyLimit: 10,
    defaultCategory: "clinical",
  },
  {
    name: "LiveScience",
    nameZh: "生活科学",
    rssUrl: "https://www.livescience.com/feeds/all",
    lang: "en",
    dailyLimit: 6,
    defaultCategory: "research",
  },
  {
    name: "Kaiser Health News",
    nameZh: "凯撒健康新闻",
    rssUrl: "https://khn.org/rss/",
    lang: "en",
    dailyLimit: 8,
    defaultCategory: "industry",
  },
  {
    name: "Stat News",
    nameZh: "Stat 医疗新闻",
    rssUrl: "https://www.statnews.com/feed/",
    lang: "en",
    dailyLimit: 8,
    defaultCategory: "industry",
  },
  {
    name: "Tech Xplore",
    nameZh: "科技探索·健康科技",
    rssUrl: "https://techxplore.com/rss-feed/",
    lang: "en",
    dailyLimit: 8,
    defaultCategory: "digital",
  },
  {
    name: "HIT Consultant",
    nameZh: "HIT 医疗数字化",
    rssUrl: "https://hitconsultant.net/feed",
    lang: "en",
    dailyLimit: 8,
    defaultCategory: "digital",
  },
  {
    name: "New Scientist Health",
    nameZh: "新科学家·健康",
    rssUrl: "https://www.newscientist.com/subject/health/feed",
    lang: "en",
    dailyLimit: 6,
    defaultCategory: "research",
  },
  // —— 咨询流派专属来源 ——
  {
    name: "Association for Behavioral & Cognitive Therapies",
    nameZh: "认知行为治疗协会 (ABCT)",
    rssUrl: "https://www.abct.org/feed/",
    lang: "en",
    dailyLimit: 8,
    defaultCategory: "clinical",
    defaultSchool: "cbt",
  },
  {
    name: "American Psychoanalytic Association",
    nameZh: "美国精神分析协会 (APsA)",
    rssUrl: "https://apsa.org/feed/",
    lang: "en",
    dailyLimit: 8,
    defaultCategory: "clinical",
    defaultSchool: "psychodynamic",
  },
  {
    name: "Behavioral Tech Institute (DBT)",
    nameZh: "行为科技学院·辩证行为疗法",
    rssUrl: "https://behavioraltech.org/feed/",
    lang: "en",
    dailyLimit: 6,
    defaultCategory: "clinical",
    defaultSchool: "dbt",
  },
  {
    name: "DBT-UK",
    nameZh: "DBT-UK 辩证行为疗法",
    rssUrl: "http://dbt-uk.com/feed/",
    lang: "en",
    dailyLimit: 6,
    defaultCategory: "clinical",
    defaultSchool: "dbt",
  },
  {
    name: "Learning ACT",
    nameZh: "Learning ACT·接纳承诺疗法",
    rssUrl: "https://learningact.com/blog/feed/",
    lang: "en",
    dailyLimit: 6,
    defaultCategory: "clinical",
    defaultSchool: "act",
  },
  {
    name: "Mindful",
    nameZh: "Mindful·正念",
    rssUrl: "https://www.mindful.org/feed/",
    lang: "en",
    dailyLimit: 6,
    defaultCategory: "education",
    defaultSchool: "mindfulness",
  },
  {
    name: "Chinese Journal of Health Psychology",
    nameZh: "中国健康心理学杂志",
    rssUrl: "http://rss.cnki.net/grid20/rss.aspx?journal=JKXL",
    lang: "zh",
    dailyLimit: 8,
    defaultCategory: "research",
  },
  {
    name: "Psychological Development and Education",
    nameZh: "心理发展与教育",
    rssUrl: "http://rss.cnki.net/grid20/rss.aspx?journal=XLFZ",
    lang: "zh",
    dailyLimit: 8,
    defaultCategory: "research",
  },
  {
    name: "Journal of Psychological Science",
    nameZh: "心理科学",
    rssUrl: "http://rss.cnki.net/grid20/rss.aspx?journal=XLKX",
    lang: "zh",
    dailyLimit: 8,
    defaultCategory: "research",
  },
  {
    name: "Chinese Mental Health Journal",
    nameZh: "中国心理卫生杂志",
    rssUrl: "http://rss.cnki.net/grid20/rss.aspx?journal=ZXWS",
    lang: "zh",
    dailyLimit: 8,
    defaultCategory: "research",
  },
  {
    name: "Psychology & Health",
    nameZh: "心理与健康",
    rssUrl: "http://rss.cnki.net/grid20/rss.aspx?journal=XLJK",
    lang: "zh",
    dailyLimit: 8,
    defaultCategory: "clinical",
  },
];
